name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -t resume-backend ./backend

      - name: Build Frontend Image
        run: docker build -t resume-frontend ./frontend